# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
 branches:
   include:
     - main
 paths:
   exclude:
     - azure-pipelines.yml

pool:
  vmImage: 'vs2017-win2016'
  #vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'


stages:
- stage: CI
  jobs:
  - job: BuildAndTest
    displayName: Build & Test

    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: VSTest@2
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

- stage: CDDev
  displayName: CD - Dev
  dependsOn: CI
  jobs:
  # Deploy to the Dev environment
  - deployment: DeployToDev
    displayName: Deploy to Dev Environment
    pool:
      vmImage: 'vs2017-win2016'
    environment: Dev
    strategy:
     runOnce:
      deploy:
        steps:
        - script: echo "Deployed to Dev"

- stage: CDProd
  displayName: CD - Prod
  dependsOn: CDDev
  jobs:
  # Deploy to Prod environment
  - deployment: DeployToProd
    displayName: Deploy to Prod Environment
    condition: succeeded()
    pool:
      vmImage: 'vs2017-win2016'
    environment: Prod
    strategy:
     runOnce:
      deploy:
        steps:
        - script: echo "Deployed to Prod"